version: "3.0"
services:
    texlive:
        container_name: LaTeX
        image: texlive/texlive:latest
        volumes:
            - ${SRC_FOLDER}:/cv
            - ${BUILD_FOLDER}:/build
        working_dir: /cv
        env_file:
            - ${SRC_FOLDER}/.config
        command: bash -c "mkdir -p /build && ${LATEX_PROGRAM} ${LATEX_ARGS} -output-directory=/build main.tex && mv /build/main.pdf /build/$${RESULT_FILENAME}.pdf"
